import { Link } from 'react-router'
import { ArrowDown, ArrowLeft, ArrowUp, CalendarDays, MapPin, Pencil, Plus, Trash2, UserPlus } from 'lucide-react'
import type { JourneyDetail } from '../store/journeyStore'
import { useLocalJourneyDetail } from './localJourney/useLocalJourneyDetail'

export default function LocalJourneyDetailPage() {
  const { zh, journey, loading, error, editing, setEditing, entryTitle, setEntryTitle, entryDate, setEntryDate, story, setStory, placeId, setPlaceId, locationName, setLocationName, places, members, showMembers, setShowMembers, selectedMember, setSelectedMember, selectedRole, setSelectedRole, showSettings, setShowSettings, settingsTitle, setSettingsTitle, settingsSubtitle, setSettingsSubtitle, settingsStatus, setSettingsStatus, tripOptions, selectedTrips, setSelectedTrips, saving, canEdit, openEditor, saveEntry, deleteEntry, moveEntry, openMembers, addMember, removeMember, removeJourney, openSettings, saveSettings, toggleArchive, changeMemberRole } = useLocalJourneyDetail()

  if (loading) return <main className="mx-auto max-w-5xl px-4 py-8 text-content-muted">{zh ? '正在读取旅程…' : 'Loading journey…'}</main>
  if (!journey) return <main className="mx-auto max-w-5xl px-4 py-8"><Link to="/journey">← {zh ? '返回旅程' : 'Back to journeys'}</Link><p role="alert" className="mt-4">{error || (zh ? '找不到旅程' : 'Journey not found')}</p></main>

  return <main className="mx-auto w-full max-w-5xl px-4 py-8 text-content-primary sm:px-8">
    <Link to="/journey" className="mb-6 inline-flex items-center gap-2 text-sm text-content-muted"><ArrowLeft size={16} />{zh ? '我的旅程' : 'My journeys'}</Link>
    <header className="mb-7 rounded-2xl border border-edge bg-surface-elevated p-5 sm:p-7">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div><h1 className="text-3xl font-bold">{journey.title}</h1>{journey.subtitle && <p className="mt-2 text-content-muted">{journey.subtitle}</p>}
          <p className="mt-3 text-sm text-content-muted">{journey.entries.length} {zh ? '条记录' : 'entries'} · {journey.trips.length} {zh ? '段旅行' : 'trips'}</p></div>
        <div className="flex flex-wrap gap-2">
          {canEdit && <button type="button" onClick={() => void openSettings()} className="inline-flex items-center gap-2 rounded-lg border border-edge px-3 py-2 text-sm"><Pencil size={15} />{zh ? '设置' : 'Settings'}</button>}
          {journey.my_role === 'owner' && <button type="button" onClick={() => void openMembers()} className="inline-flex items-center gap-2 rounded-lg border border-edge px-3 py-2 text-sm"><UserPlus size={15} />{zh ? '成员' : 'Members'}</button>}
          {canEdit && <button type="button" onClick={() => openEditor('new')} className="inline-flex items-center gap-2 rounded-lg bg-inverse px-3 py-2 text-sm text-inverse-text"><Plus size={15} />{zh ? '添加记录' : 'Add entry'}</button>}
        </div>
      </div>
      {journey.trips.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{journey.trips.map(trip => <span key={trip.trip_id} className="rounded-full bg-surface-selected px-3 py-1 text-xs">{trip.title}</span>)}</div>}
    </header>
    {error && <p role="alert" className="mb-4 rounded-lg bg-red-100 px-4 py-3 text-sm text-red-800">{error}</p>}
    {journey.entries.length === 0 ? <div className="rounded-2xl border border-edge bg-surface-elevated px-6 py-14 text-center text-content-muted"><CalendarDays className="mx-auto mb-3" size={30} />{zh ? '还没有文字记录。' : 'No entries yet.'}</div> :
      <div className="space-y-4">{journey.entries.map((entry, index) => <article key={entry.id} className="rounded-2xl border border-edge bg-surface-elevated p-5">
        <div className="mb-2 flex items-start justify-between gap-3"><div><time className="text-xs text-content-muted">{entry.entry_date}</time><h2 className="mt-1 text-xl font-semibold">{entry.title || (zh ? '未命名记录' : 'Untitled entry')}</h2></div>
          {canEdit && <div className="flex gap-1"><button type="button" onClick={() => void moveEntry(index, -1)} disabled={index === 0 || journey.entries[index - 1].entry_date !== entry.entry_date} aria-label={zh ? '上移' : 'Move up'} className="rounded-lg p-2 hover:bg-surface-selected disabled:opacity-30"><ArrowUp size={15} /></button><button type="button" onClick={() => void moveEntry(index, 1)} disabled={index === journey.entries.length - 1 || journey.entries[index + 1].entry_date !== entry.entry_date} aria-label={zh ? '下移' : 'Move down'} className="rounded-lg p-2 hover:bg-surface-selected disabled:opacity-30"><ArrowDown size={15} /></button><button type="button" onClick={() => openEditor(entry)} aria-label={zh ? '编辑' : 'Edit'} className="rounded-lg p-2 hover:bg-surface-selected"><Pencil size={15} /></button><button type="button" onClick={() => void deleteEntry(entry)} aria-label={zh ? '删除' : 'Delete'} className="rounded-lg p-2 hover:bg-surface-selected"><Trash2 size={15} /></button></div>}</div>
        {entry.location_name && <p className="mb-3 flex items-center gap-1 text-sm text-content-muted"><MapPin size={14} />{entry.location_name}</p>}
        {entry.story && <p className="whitespace-pre-wrap text-sm leading-7">{entry.story}</p>}
      </article>)}</div>}
    {journey.my_role === 'owner' && <div className="mt-10 flex flex-wrap gap-3 border-t border-edge pt-5">
      <button type="button" onClick={() => void toggleArchive()} className="rounded-lg border border-edge px-3 py-2 text-sm">{journey.status === 'archived' ? (zh ? '重新启用' : 'Reopen') : (zh ? '归档旅程' : 'Archive journey')}</button>
      <button type="button" onClick={() => void removeJourney()} className="rounded-lg border border-red-400 px-3 py-2 text-sm text-red-600">{zh ? '删除旅程' : 'Delete journey'}</button>
    </div>}
    {editing && <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/60 p-4" role="presentation" onClick={() => setEditing(null)}><section role="dialog" aria-modal="true" aria-label={zh ? '编辑记录' : 'Edit entry'} className="w-full max-w-xl rounded-2xl bg-surface-elevated p-6" onClick={event => event.stopPropagation()}>
      <h2 className="mb-4 text-xl font-semibold">{editing === 'new' ? (zh ? '添加记录' : 'Add entry') : (zh ? '编辑记录' : 'Edit entry')}</h2>
      <div className="grid gap-3"><label className="text-sm">{zh ? '日期' : 'Date'}<input type="date" value={entryDate} onChange={event => setEntryDate(event.target.value)} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2" /></label>
        <label className="text-sm">{zh ? '标题' : 'Title'}<input value={entryTitle} onChange={event => setEntryTitle(event.target.value)} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2" /></label>
        <label className="text-sm">{zh ? '旅行地点（选填）' : 'Trip place (optional)'}<select value={placeId} onChange={event => { setPlaceId(event.target.value); setLocationName(places.find(place => String(place.id) === event.target.value)?.name ?? '') }} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2"><option value="">{zh ? '不关联地点' : 'No place'}</option>{places.map(place => <option key={place.id} value={place.id}>{place.name}</option>)}</select></label>
        <label className="text-sm">{zh ? '地点名称（可手动填写）' : 'Place name (optional)'}<input value={locationName} onChange={event => setLocationName(event.target.value)} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2" /></label>
        <label className="text-sm">{zh ? '记录' : 'Story'}<textarea value={story} onChange={event => setStory(event.target.value)} rows={8} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2" /></label></div>
      <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setEditing(null)} className="rounded-lg border border-edge px-4 py-2">{zh ? '取消' : 'Cancel'}</button><button type="button" onClick={() => void saveEntry()} disabled={saving || !entryDate} className="rounded-lg bg-inverse px-4 py-2 text-inverse-text disabled:opacity-50">{saving ? '…' : zh ? '保存' : 'Save'}</button></div>
    </section></div>}
    {showMembers && <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/60 p-4" role="presentation" onClick={() => setShowMembers(false)}><section role="dialog" aria-modal="true" aria-label={zh ? '旅程成员' : 'Journey members'} className="w-full max-w-lg rounded-2xl bg-surface-elevated p-6" onClick={event => event.stopPropagation()}>
      <h2 className="mb-4 text-xl font-semibold">{zh ? '旅程成员' : 'Journey members'}</h2>
      <div className="mb-5 space-y-2">{journey.contributors.map(member => <div key={member.user_id} className="flex items-center justify-between gap-2 rounded-lg border border-edge px-3 py-2 text-sm"><span>{member.username}</span>{member.role === 'owner' ? <span>{zh ? '所有者' : 'Owner'}</span> : <div className="flex items-center gap-2"><select aria-label={zh ? '成员权限' : 'Member role'} value={member.role} onChange={event => void changeMemberRole(member.user_id, event.target.value as 'editor' | 'viewer')} className="rounded-lg border border-edge bg-surface px-2 py-1"><option value="editor">{zh ? '编辑' : 'Editor'}</option><option value="viewer">{zh ? '查看' : 'Viewer'}</option></select><button type="button" onClick={() => void removeMember(member.user_id)} className="text-red-600">{zh ? '移除' : 'Remove'}</button></div>}</div>)}</div>
      <div className="grid gap-2 sm:grid-cols-[1fr_auto_auto]"><select value={selectedMember} onChange={event => setSelectedMember(event.target.value)} className="rounded-lg border border-edge bg-surface px-3 py-2 text-sm"><option value="">{zh ? '选择工作区成员' : 'Select workspace member'}</option>{members.filter(person => !journey.contributors.some(member => member.user_id === person.id)).map(person => <option key={person.id} value={person.id}>{person.display_name || person.username}</option>)}</select><select value={selectedRole} onChange={event => setSelectedRole(event.target.value as 'editor' | 'viewer')} className="rounded-lg border border-edge bg-surface px-3 py-2 text-sm"><option value="editor">{zh ? '编辑' : 'Editor'}</option><option value="viewer">{zh ? '查看' : 'Viewer'}</option></select><button type="button" onClick={() => void addMember()} disabled={!selectedMember || saving} className="rounded-lg bg-inverse px-3 py-2 text-sm text-inverse-text disabled:opacity-50">{zh ? '添加' : 'Add'}</button></div>
      <div className="mt-5 text-right"><button type="button" onClick={() => setShowMembers(false)} className="rounded-lg border border-edge px-4 py-2 text-sm">{zh ? '完成' : 'Done'}</button></div>
    </section></div>}
    {showSettings && <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/60 p-4" role="presentation" onClick={() => setShowSettings(false)}><section role="dialog" aria-modal="true" aria-label={zh ? '旅程设置' : 'Journey settings'} className="w-full max-w-lg rounded-2xl bg-surface-elevated p-6" onClick={event => event.stopPropagation()}>
      <h2 className="mb-4 text-xl font-semibold">{zh ? '旅程设置' : 'Journey settings'}</h2>
      <label className="mb-3 block text-sm">{zh ? '名称' : 'Name'}<input value={settingsTitle} onChange={event => setSettingsTitle(event.target.value)} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2" /></label>
      <label className="mb-3 block text-sm">{zh ? '副标题' : 'Subtitle'}<input value={settingsSubtitle} onChange={event => setSettingsSubtitle(event.target.value)} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2" /></label>
      <label className="mb-3 block text-sm">{zh ? '状态' : 'Status'}<select value={settingsStatus} onChange={event => setSettingsStatus(event.target.value as JourneyDetail['status'])} className="mt-1 w-full rounded-lg border border-edge bg-surface px-3 py-2"><option value="draft">{zh ? '草稿' : 'Draft'}</option><option value="active">{zh ? '进行中' : 'Active'}</option><option value="completed">{zh ? '已完成' : 'Completed'}</option><option value="archived">{zh ? '已归档' : 'Archived'}</option></select></label>
      <fieldset className="max-h-48 overflow-y-auto rounded-lg border border-edge p-3"><legend className="px-1 text-sm">{zh ? '关联旅行' : 'Linked trips'}</legend>{tripOptions.map(trip => <label key={trip.id} className="flex items-center gap-2 py-1.5 text-sm"><input type="checkbox" checked={selectedTrips.includes(trip.id)} onChange={event => setSelectedTrips(prev => event.target.checked ? [...prev, trip.id] : prev.filter(id => id !== trip.id))} />{trip.title}</label>)}</fieldset>
      <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setShowSettings(false)} className="rounded-lg border border-edge px-4 py-2">{zh ? '取消' : 'Cancel'}</button><button type="button" onClick={() => void saveSettings()} disabled={!settingsTitle.trim() || saving} className="rounded-lg bg-inverse px-4 py-2 text-inverse-text disabled:opacity-50">{zh ? '保存' : 'Save'}</button></div>
    </section></div>}
  </main>
}
