-- TREK Supabase identity foundation. Business/trip data remains in IndexedDB
-- during this phase; auth.users.id is the canonical user identity going forward.

create type public.trek_user_role as enum ('admin', 'user');
create type public.trek_profile_status as enum ('active', 'disabled');
create type public.trek_workspace_kind as enum ('personal', 'shared');
create type public.trek_workspace_role as enum ('owner', 'admin', 'member');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  -- Transitional bridge for the current numeric TREK model and IndexedDB names.
  -- New cloud relations must use profiles.id, never this compatibility column.
  legacy_user_id bigint generated by default as identity unique not null,
  username text not null check (char_length(trim(username)) between 1 and 64),
  display_name text not null check (char_length(trim(display_name)) between 1 and 100),
  role public.trek_user_role not null default 'user',
  status public.trek_profile_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index profiles_username_ci_unique on public.profiles (lower(username));
create index profiles_role_status_idx on public.profiles (role, status);

create table public.workspaces (
  id uuid primary key default gen_random_uuid(),
  kind public.trek_workspace_kind not null,
  name text not null check (char_length(trim(name)) between 1 and 100),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index workspaces_one_personal_per_owner
on public.workspaces (owner_id)
where kind = 'personal';

create table public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.trek_workspace_role not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create index workspace_members_user_idx on public.workspace_members (user_id, workspace_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger workspaces_set_updated_at
before update on public.workspaces
for each row execute function public.set_updated_at();

create trigger workspace_members_set_updated_at
before update on public.workspace_members
for each row execute function public.set_updated_at();

create or replace function public.create_personal_workspace()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  workspace_uuid uuid;
begin
  insert into public.workspaces (kind, name, owner_id)
  values ('personal', new.display_name || ' 的个人空间', new.id)
  returning id into workspace_uuid;

  insert into public.workspace_members (workspace_id, user_id, role)
  values (workspace_uuid, new.id, 'owner');
  return new;
end;
$$;

create trigger profiles_create_personal_workspace
after insert on public.profiles
for each row execute function public.create_personal_workspace();

create or replace function public.create_profile_for_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_username text;
  requested_display_name text;
begin
  requested_username := nullif(trim(new.raw_user_meta_data ->> 'username'), '');
  requested_display_name := nullif(trim(new.raw_user_meta_data ->> 'display_name'), '');

  insert into public.profiles (id, username, display_name, role, status)
  values (
    new.id,
    coalesce(requested_username, 'user-' || substr(new.id::text, 1, 8)),
    coalesce(requested_display_name, requested_username, 'TREK User'),
    'user',
    'active'
  );
  return new;
end;
$$;

create trigger auth_user_create_profile
after insert on auth.users
for each row execute function public.create_profile_for_auth_user();

-- Bind the already-created Supabase Auth account to TREK's existing local admin.
insert into public.profiles (
  id, legacy_user_id, username, display_name, role, status
)
values (
  '3c29e1b8-20b6-46ee-a40f-4cacefeba368',
  1,
  'admin',
  'admin',
  'admin',
  'active'
)
on conflict (id) do update set
  legacy_user_id = excluded.legacy_user_id,
  username = excluded.username,
  display_name = excluded.display_name,
  role = excluded.role,
  status = excluded.status,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.profiles', 'legacy_user_id'),
  greatest((select coalesce(max(legacy_user_id), 1) from public.profiles), 1),
  true
);

create or replace function public.is_trek_admin(candidate uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = candidate and role = 'admin' and status = 'active'
  );
$$;

create or replace function public.is_workspace_member(candidate_workspace uuid, candidate_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members
    where workspace_id = candidate_workspace and user_id = candidate_user
  );
$$;

revoke all on function public.is_trek_admin(uuid) from public;
revoke all on function public.is_workspace_member(uuid, uuid) from public;
grant execute on function public.is_trek_admin(uuid) to authenticated;
grant execute on function public.is_workspace_member(uuid, uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;

create policy profiles_select_own_or_admin
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_trek_admin(auth.uid()));

create policy workspaces_select_member_or_admin
on public.workspaces for select to authenticated
using (public.is_workspace_member(id, auth.uid()) or public.is_trek_admin(auth.uid()));

create policy workspace_members_select_member_or_admin
on public.workspace_members for select to authenticated
using (public.is_workspace_member(workspace_id, auth.uid()) or public.is_trek_admin(auth.uid()));

-- No direct client writes in phase one. Profile and membership mutations go
-- through authenticated Edge Functions after server-side role validation.
revoke all on public.profiles, public.workspaces, public.workspace_members from anon;
grant select on public.profiles, public.workspaces, public.workspace_members to authenticated;
